// <auto-generated />
using System;
using BillGeneratorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillGeneratorAPI.Migrations
{
    [DbContext(typeof(BillGeneratorDbContext))]
    partial class BillGeneratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillGeneratorAPI.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DraftSavedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Catalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogType");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogType = "entrance",
                            Category = "Entrance Fee",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5245),
                            Name = "Adult",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            CatalogType = "entrance",
                            Category = "Entrance Fee",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5262),
                            Name = "Child",
                            Price = 25m
                        },
                        new
                        {
                            Id = 3,
                            CatalogType = "entrance",
                            Category = "Entrance Fee",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5264),
                            Name = "Senior",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            CatalogType = "entrance",
                            Category = "Entrance Fee",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5266),
                            Name = "VIP",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            CatalogType = "donation",
                            Category = "Donation",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5267),
                            Name = "Small Donation",
                            Price = 100m
                        },
                        new
                        {
                            Id = 6,
                            CatalogType = "donation",
                            Category = "Donation",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5269),
                            Name = "Medium Donation",
                            Price = 500m
                        },
                        new
                        {
                            Id = 7,
                            CatalogType = "donation",
                            Category = "Donation",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5270),
                            Name = "Large Donation",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 8,
                            CatalogType = "selling",
                            Category = "Merchandise",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5272),
                            Name = "T-Shirt",
                            Price = 200m
                        },
                        new
                        {
                            Id = 9,
                            CatalogType = "selling",
                            Category = "Merchandise",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5273),
                            Name = "Cap",
                            Price = 150m
                        },
                        new
                        {
                            Id = 10,
                            CatalogType = "selling",
                            Category = "Food & Beverage",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5274),
                            Name = "Water Bottle",
                            Price = 100m
                        },
                        new
                        {
                            Id = 11,
                            CatalogType = "selling",
                            Category = "Food & Beverage",
                            CreatedDate = new DateTime(2026, 4, 4, 12, 38, 43, 41, DateTimeKind.Local).AddTicks(5276),
                            Name = "Snacks",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.BillItem", b =>
                {
                    b.HasOne("BillGeneratorAPI.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
